server:
  host: "0.0.0.0"
  port: 3000

features:
  upload: true
  privateFiles: true
  homePage: true
  publicTrafficLimits: false

directories:
  public: "~/.local/stream-file-server/public"
  upload: "~/.local/stream-file-server/files"
  incoming: "~/.local/stream-file-server/files/incoming"
  private: "~/.local/stream-file-server/files/private-files"
